theme: jekyll-theme-profile
style: sidebar # One of "stacked", "sidebar", "topbar"
repository: athackst/athackst.github.io
title: althack.dev

repositories:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 24
  exclude:
    archived: true
    forks: true
    repositories:
      - athackst.github.io
      - athackst.mkdocs

social_media:
  # behance: your_username
  # dribbble: your_username
  docker: althack
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: allisonthackston
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: althack
  # unsplash: your_username
  # vk: your_username
  vscode: althack
  website: https://www.allisonthackston.com
  # youtube: your_username

analytics:
  provider: google
  property: G-JG29YKVRKH

links:
  - name: Website
    url: https://www.allisonthackston.com
    thumbnail: https://www.allisonthackston.com/assets/img/profile.jpg
    description: My personal website + blog

  - name: Dashboard
    url: https://dashboard.althack.dev
    thumbnail: https://dashboard.althack.dev/assets/dashboard.png
    description: My GitHub Dashboard showing the status of all of my repos

  - name: NASA JSC
    url: https://gitlab.com/nasa-jsc-robotics
    thumbnail: https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/2449px-NASA_logo.svg.png
    description: NASA JSC Robonaut + Valkyrie open source libraries

  - name: Task Behavior Tree
    url: https://github.com/ToyotaResearchInstitute/task_behavior_engine
    thumbnail: https://upload.wikimedia.org/wikipedia/commons/1/15/Robot_Operating_System_logo.svg
    description: Behavior tree engine for ROS1

  - name: Women in Robotics
    url: https://womeninrobotics.org
    thumbnail: https://www.womeninrobotics.org/assets/images/logo/WiRLogo-200x200t.png
