github: [metadata]
plugins:
  - jekyll-feed

url: http://lyonthackston.com
title: Allison Thackston
author: Allison Thackston
description: >  
  Allison Thackston, Roboticist / Engineering Lead and Manager.
copyright: 'Copyright &copy; 2014 Allison Thackston. All Rights Reserved.'