github: [metadata]
permalink: pretty

url: https://www.allisonthackston.com
meta_url: https://www.allisonthackston.com
title: Allison Thackston
author: Allison Thackston
twitter_username: althack
title_image: /assets/img/IMG_5118.jpg
description: >  
  Allison Thackston, Roboticist && Engineering Lead and Manager.

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - github-pages
  - jekyll-redirect-from # Set up custom redirects

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

whitelist: 
  - jekyll-redirect-from

collections:
  articles:
    output: true
    permalink: /:collection/:name:output_ext

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: text_entry
      toc: true
