theme: jekyll-theme-primerpages
style: appbar # One of "stacked", "sidebar", "topbar"
repository: athackst/athackst.github.io
title: althack.dev

repositories:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 24
  exclude:
    archived: true
    forks: true
    repositories:
      - athackst.github.io
      - athackst.mkdocs

social_media:
  # behance: your_username
  # dribbble: your_username
  docker: althack
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: allisonthackston
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  x: althack
  # unsplash: your_username
  # vk: your_username
  vscode: althack
  # youtube: your_username

analytics:
  provider: google
  property: G-JG29YKVRKH

exclude:
 - bin
 - .ruby-lsp/*
 - node_modules/*
 - vendor/*
 - .sass-cache/*
 - .cookies

plugins:
  - jekyll-redirect-from
