github: [metadata]
plugins:
  - jekyll-feed

url: http://lyonthackston.com
title: Allison Lyon Thackston
email: allison@lyonthackston.com
author: Allison Lyon Thackston
description: >  
  Allison Thackston, Roboticist / Engineering Lead and Manager.
copyright: 'Copyright &copy; 2014 Allison Thackston. All Rights Reserved.'

post-img-location: /assets/img/posts