github: [metadata]
permalink: pretty

url: https://www.allisonthackston.com
meta_url: https://www.allisonthackston.com
title: Allison Thackston
author: Allison Thackston
twitter_username: althack
title_image: /assets/img/IMG_5118.jpg
description: >  
  Allison Thackston, Roboticist && Engineering Lead and Manager.


# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - github-pages
  - jekyll-redirect-from # Set up custom redirects
  - jemoji # Github flavored emoji

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

whitelist: 
  - jekyll-redirect-from

defaults:
  - scope:
      path: "articles"
      type: "posts"
    values:
      layout: text-entry
      permalink: /articles/:title:output_ext
      toc: true
