---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: articles/_posts
  label: Articles
  create: all
  match: "**/*"
- type: directory
  path: experience/_posts
  label: Experience
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/img
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bash -c "bundle config set path vendor/bundle && bundle install"
  preview_docker_image: athackst/github:pages-dev
  mount_path: "/srv/athackst.github.io"
  working_dir: "/srv/athackst.github.io"
  instant_preview_command: bash -c "bundle config set path vendor/bundle && bundle exec jekyll serve --drafts --unpublished --future --incremental -d _site"
