name: Test site
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Not needed with a .ruby-version file
      - name: Setup bundle
        run: |
          bundle install
          bundle exec jekyll build
      - name: HtmlProofer
        run: .github/htmlproofer.sh
