name: Test
on: [push]

jobs:
  test-site:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
    - run: bundle install
    - run: bundle exec jekyll build