name: Test site
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Not needed with a .ruby-version file
      - name: Setup bundle
        run: |
          bundle install
      - name: Build site
        run: |
          bundle exec jekyll build
      - name: HtmlProofer
        run: |
          ruby .github/htmlproofer.rb
